language: node_js
node_js: "lts/*"
services:
  - xvfb
before_install:
  - 'npm install -g typescript'
install:
  - 'npm install'
  - 'npm install -g vsce'
  - 'vsce package'
cache:
  directories:
    - "node_modules"
env: DISPLAY=:99
branches:
  except:
    - /^dependabot.*$/
